# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
     aws cloudformation create-stack --stack-name BlueGreenDeploymentStack --template-body file://blue-green-aws-infa-.yml --parameters file://config.json
  displayName: 'Create Stack'
